# Accelerate Configuration for MedGemma Training
# Run `accelerate config` to customize this interactively

compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU  # Change to NO if single GPU
mixed_precision: bf16
use_cpu: false
num_processes: 1  # Set to number of GPUs
num_machines: 1
machine_rank: 0
main_process_ip: null
main_process_port: null
rdzv_backend: static
same_network: true
main_training_function: main
downcast_bf16: 'no'
enable_cpu_affinity: false
